# Generated by Django 6.0.2 on 2026-02-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_status_client_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('AV', 'Agente de Ventas'), ('PS', 'Personal Shopper'), ('BOTH', 'Ambos (AV y PS)')], default='AV', max_length=4),
        ),
    ]
