# Generated by Django 6.0.2 on 2026-02-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='shipping_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productitem',
            name='taxes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
