# Generated by Django 6.0.2 on 2026-02-28 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_productitem_image_productitem_shipping_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='api.client'),
        ),
    ]
