# Generated by Django 6.0.2 on 2026-02-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_receipt_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='shipping_paid',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='taxes',
        ),
        migrations.AddField(
            model_name='receipt',
            name='shipping_paid',
            field=models.BooleanField(default=False),
        ),
    ]
