# Generated by Django 6.0.2 on 2026-02-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_productitem_shipping_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Misión Activa'), ('PAUSED', 'Misión Pausada'), ('COMPLETED', 'Misión Finalizada')], default='ACTIVE', max_length=50),
        ),
    ]
