# Generated by Django 6.0.2 on 2026-02-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_client_email_client_phone_client_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de Compra'), ('BOUGHT', 'Comprado'), ('PAID', 'Pagado por Cliente'), ('SHIPPED', 'Enviado')], default='PENDING', max_length=50),
        ),
    ]
