# Generated by Django 6.0.2 on 2026-03-02 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# <-------- seccion 7: migracion de revisiones y alternativas

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('CHECK_SIZE', 'Verificar talla/tamaño'), ('CHECK_STOCK', 'Verificar existencia'), ('CHECK_OTHER', 'Otro')], default='CHECK_OTHER', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('NO_STOCK', 'No existencia'), ('ALTERNATIVE_SENT', 'Alternativa enviada'), ('REPLACED', 'Reemplazado'), ('DISCARDED', 'Descartado')], default='PENDING', max_length=20)),
                ('review_note', models.TextField()),
                ('ps_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='api.productitem')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='alternatives/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='api.productreview')),
            ],
        ),
    ]
