# Generated by Django 6.0.2 on 2026-03-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_productreview_reviewalternative'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
