# Generated by Django 6.0.2 on 2026-03-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_userprofile_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='calc_mode',
            field=models.CharField(choices=[('FACTOR', 'Factor'), ('PERCENTAGE', 'Porcentaje')], default='FACTOR', max_length=20),
        ),
        migrations.AddField(
            model_name='mission',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mission',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mission',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=17.5, max_digits=10),
        ),
        migrations.AddField(
            model_name='mission',
            name='factor_value',
            field=models.DecimalField(decimal_places=4, default=1.5, max_digits=8),
        ),
        migrations.AddField(
            model_name='mission',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mission',
            name='ticket_image',
            field=models.ImageField(blank=True, null=True, upload_to='mission_tickets/'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='status',
            field=models.CharField(choices=[('ANNOTATED', 'Anotado'), ('IN_REVIEW', 'En Revision'), ('BOUGHT', 'Comprado'), ('SHIPPED', 'Enviado'), ('REJECTED', 'Rechazado')], default='ANNOTATED', max_length=50),
        ),
    ]
