# Generated by Codex on 2026-03-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_mission_calc_mode_mission_commission_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='client',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='requests',
                to='api.client',
            ),
        ),
        migrations.AddField(
            model_name='request',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='requests/'),
        ),
    ]
