# Generated by Codex on 2026-03-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_request_client_request_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='store',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='missions',
                to='api.store',
            ),
        ),
    ]
